// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kahanSum
double kahanSum(NumericVector x);
RcppExport SEXP _jaccard_kahanSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(kahanSum(x));
    return rcpp_result_gen;
END_RCPP
}
// kahanCumSum
NumericVector kahanCumSum(NumericVector x);
RcppExport SEXP _jaccard_kahanCumSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(kahanCumSum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jaccard_kahanSum", (DL_FUNC) &_jaccard_kahanSum, 1},
    {"_jaccard_kahanCumSum", (DL_FUNC) &_jaccard_kahanCumSum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_jaccard(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
