# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kahanSum <- function(x) {
    .Call('_jaccard_kahanSum', PACKAGE = 'jaccard', x)
}

kahanCumSum <- function(x) {
    .Call('_jaccard_kahanCumSum', PACKAGE = 'jaccard', x)
}

